// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {domain} from '../models';

export function ApplicationInfo():Promise<main.ApplicationInfo>;

export function ChooseExportFolder(arg1:string):Promise<string>;

export function ChooseImportFile(arg1:string):Promise<string>;

export function ChooseImportTargetFolder(arg1:string):Promise<string>;

export function DefaultClaudeRoot():Promise<string>;

export function DefaultClaudeSidebarRoot():Promise<string>;

export function DefaultCodexRoot():Promise<string>;

export function ExecuteCodexImport(arg1:string):Promise<domain.CodexImportExecutionResult>;

export function ExecuteSyntheticImport(arg1:string,arg2:string,arg3:boolean):Promise<domain.ImportExecutionResult>;

export function ExecuteTransferImport(arg1:string):Promise<domain.TransferImportExecutionResult>;

export function ExportClaude(arg1:string,arg2:domain.ExportRequest):Promise<domain.ExportResult>;

export function ExportCodex(arg1:string,arg2:domain.ExportRequest):Promise<domain.ExportResult>;

export function ExportSynthetic(arg1:domain.ExportRequest):Promise<domain.ExportResult>;

export function InspectCodexImport(arg1:string,arg2:string):Promise<domain.CodexImportInspection>;

export function InspectTransferImport(arg1:string,arg2:string,arg3:string):Promise<domain.TransferImportInspection>;

export function OpenExportFolder(arg1:string):Promise<void>;

export function PlanSyntheticImport(arg1:string,arg2:Array<domain.TargetProject>):Promise<domain.ImportPlan>;

export function PreflightSyntheticImport(arg1:string,arg2:string,arg3:boolean):Promise<domain.ImportPreflight>;

export function PrepareCodexImport(arg1:domain.CodexImportRequest):Promise<domain.CodexImportPreflight>;

export function PrepareTransferImport(arg1:domain.TransferImportRequest):Promise<domain.TransferImportPreflight>;

export function ProbeCodexRoot(arg1:string):Promise<domain.CodexProbe>;

export function ScanClaudeRoot(arg1:string):Promise<domain.ScanResult>;

export function ScanCodexRoot(arg1:string):Promise<domain.ScanResult>;

export function ScanSynthetic():Promise<domain.ScanResult>;

export function ValidateBundle(arg1:string):Promise<domain.BundleValidation>;
