// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationInfo() {
  return window['go']['main']['App']['ApplicationInfo']();
}

export function ChooseExportFolder(arg1) {
  return window['go']['main']['App']['ChooseExportFolder'](arg1);
}

export function ChooseImportFile(arg1) {
  return window['go']['main']['App']['ChooseImportFile'](arg1);
}

export function ChooseImportTargetFolder(arg1) {
  return window['go']['main']['App']['ChooseImportTargetFolder'](arg1);
}

export function DefaultClaudeRoot() {
  return window['go']['main']['App']['DefaultClaudeRoot']();
}

export function DefaultClaudeSidebarRoot() {
  return window['go']['main']['App']['DefaultClaudeSidebarRoot']();
}

export function DefaultCodexRoot() {
  return window['go']['main']['App']['DefaultCodexRoot']();
}

export function ExecuteCodexImport(arg1) {
  return window['go']['main']['App']['ExecuteCodexImport'](arg1);
}

export function ExecuteSyntheticImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSyntheticImport'](arg1, arg2, arg3);
}

export function ExecuteTransferImport(arg1) {
  return window['go']['main']['App']['ExecuteTransferImport'](arg1);
}

export function ExportClaude(arg1, arg2) {
  return window['go']['main']['App']['ExportClaude'](arg1, arg2);
}

export function ExportCodex(arg1, arg2) {
  return window['go']['main']['App']['ExportCodex'](arg1, arg2);
}

export function ExportSynthetic(arg1) {
  return window['go']['main']['App']['ExportSynthetic'](arg1);
}

export function InspectCodexImport(arg1, arg2) {
  return window['go']['main']['App']['InspectCodexImport'](arg1, arg2);
}

export function InspectTransferImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['InspectTransferImport'](arg1, arg2, arg3);
}

export function OpenExportFolder(arg1) {
  return window['go']['main']['App']['OpenExportFolder'](arg1);
}

export function PlanSyntheticImport(arg1, arg2) {
  return window['go']['main']['App']['PlanSyntheticImport'](arg1, arg2);
}

export function PreflightSyntheticImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreflightSyntheticImport'](arg1, arg2, arg3);
}

export function PrepareCodexImport(arg1) {
  return window['go']['main']['App']['PrepareCodexImport'](arg1);
}

export function PrepareTransferImport(arg1) {
  return window['go']['main']['App']['PrepareTransferImport'](arg1);
}

export function ProbeCodexRoot(arg1) {
  return window['go']['main']['App']['ProbeCodexRoot'](arg1);
}

export function ScanClaudeRoot(arg1) {
  return window['go']['main']['App']['ScanClaudeRoot'](arg1);
}

export function ScanCodexRoot(arg1) {
  return window['go']['main']['App']['ScanCodexRoot'](arg1);
}

export function ScanSynthetic() {
  return window['go']['main']['App']['ScanSynthetic']();
}

export function ValidateBundle(arg1) {
  return window['go']['main']['App']['ValidateBundle'](arg1);
}
